"""Build the leaderboard tables on the HazEvalHub landslides page.

Writes two includes read by book/chapters/hazevalhub-landslides.md:

- book/chapters/includes/landslides-classification.md
    Task L1. One row per entry in data/hazevalhub/landslides_classification.csv.
    Add a model by adding a row, then rerun this script.
- book/chapters/includes/landslides-detection.md
    Task L2. The QuakeXNet row is computed from the stored outputs of
    notebooks/analyzing_quakexnet_15_years_detection_results.ipynb in
    Akashkharita/pnw_seismic_event_detection at a pinned commit (read, not rerun).

Run from the repo root (L2 needs network access):

    pixi run python scripts/hazevalhub/landslides_leaderboard.py

To refresh L2, change DET_SHA and rerun. Edit this file and the CSV, not the includes.
"""

import csv
import json
import re
import urllib.request
from pathlib import Path

DET_REPO = "Akashkharita/pnw_seismic_event_detection"
DET_SHA = "d91b386a8744eaf55753fc50d73d26e214f4b155"  # 2026-09-08

ROOT = Path(__file__).resolve().parents[2]
L1_CSV = ROOT / "data" / "hazevalhub" / "landslides_classification.csv"
INC = ROOT / "book" / "chapters" / "includes"
HEADER = "<!-- Generated by scripts/hazevalhub/landslides_leaderboard.py. Do not edit by hand. -->\n"


def fetch(repo, sha, path):
    url = f"https://raw.githubusercontent.com/{repo}/{sha}/{path}"
    with urllib.request.urlopen(url, timeout=120) as r:
        return r.read().decode("utf-8")


def cell_text(cell):
    out = []
    for o in cell.get("outputs", []):
        if o.get("output_type") == "stream":
            out.append("".join(o["text"]))
        elif "text/plain" in o.get("data", {}):
            out.append("".join(o["data"]["text/plain"]))
    return "\n".join(out)


def find_output(nb, marker):
    for c in nb["cells"]:
        t = cell_text(c)
        if marker in t:
            return t
    raise SystemExit(f"marker not found in notebook outputs: {marker!r}")


def num(s):
    return int(s.replace(",", ""))


def write_l1():
    rows = list(csv.DictReader(L1_CSV.open()))
    rows.sort(key=lambda r: (-float(r["f1_pct"]), -float(r["accuracy_pct"])))
    lines = [HEADER,
             "| Rank | Model | Input | F1 % | Acc. % | Params | MB | s/day | Source |",
             "|---:|---|---|---:|---:|---:|---:|---:|---|"]
    rank, prev = 0, None
    for i, r in enumerate(rows, 1):
        key = (r["f1_pct"], r["accuracy_pct"])
        if key != prev:
            rank, prev = i, key
        name = f"**{r['model']}**" if r["model"].startswith("QuakeXNet") else r["model"]
        params = f"{int(r['parameters']):,}" if r["parameters"] else "n/r"
        lines.append(
            f"| {rank} | {name} | {r['input']} | {r['f1_pct']} | "
            f"{r['accuracy_pct']} | {params} | {r['memory_mb'] or 'n/r'} | "
            f"{r['seconds_per_station_day'] or 'n/r'} | [paper]({r['source_url']}) · "
            f"[code]({r['code']}) |")
    lines += ["", "Z: vertical component only. n/r: not reported in the source. "
              "Sorted by F1, then accuracy; ties share a rank."]
    (INC / "landslides-classification.md").write_text("\n".join(lines) + "\n")


def load_pnsn():
    nb = json.loads(fetch(DET_REPO, DET_SHA,
                          "notebooks/analyzing_quakexnet_15_years_detection_results.ipynb"))
    t = find_output(nb, "=== MATCHING RESULTS ===")
    r = {"recall": {k: (int(a), int(b)) for k, a, b in
                    re.findall(r"^\s+(su|px): (\d+)/(\d+) = ", t, re.M)}}
    conf = {}
    for row in ("px", "su"):
        m = re.search(rf"^{row}\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)$", t, re.M)
        conf[row] = dict(zip(("eq", "px", "su", "all"), map(int, m.groups())))
    r["confusion"] = conf
    r["novel"] = num(re.search(r"Total novel detections: ([\d,]+)", t).group(1))
    return r


def write_l2():
    p = load_pnsn()
    (ksu, nsu), (kpx, npx) = p["recall"]["su"], p["recall"]["px"]
    c = p["confusion"]
    src = (f"[notebook @{DET_SHA[:7]}](https://github.com/{DET_REPO}/blob/"
           f"{DET_SHA}/notebooks/analyzing_quakexnet_15_years_detection_results.ipynb)")
    lines = [HEADER,
             "| Rank | Model | su recall % | px recall % | su label % | px label % "
             "| Not in PNSN | Precision | Source |",
             "|---:|---|---:|---:|---:|---:|---:|---|---|",
             f"| 1 | **QuakeXNet (2D) v3** | {100 * ksu / nsu:.1f} | {100 * kpx / npx:.1f} | "
             f"{100 * c['su']['su'] / c['su']['all']:.1f} | "
             f"{100 * c['px']['px'] / c['px']['all']:.1f} | {p['novel']:,} | not measured | {src} |",
             "",
             f"Recall is over {nsu:,} PNSN surface events and {npx:,} PNSN explosions. Values are "
             "read from stored notebook outputs and were not rerun."]
    (INC / "landslides-detection.md").write_text("\n".join(lines) + "\n")


def main():
    INC.mkdir(parents=True, exist_ok=True)
    write_l1()
    write_l2()
    print("wrote", ", ".join(str(q.relative_to(ROOT)) for q in sorted(INC.glob("landslides-*.md"))))


if __name__ == "__main__":
    main()
