#!/usr/bin/env python3
"""
Regenerate the GAIA knowledge-graph data block in gaia-knowledge-graph.html
from graph-data.yml (the single source of truth).

Usage:
    python book/graph/build_graph.py            # regenerate + validate + drift report
    python book/graph/build_graph.py --check     # validate only, fail on error, write nothing
    python book/graph/build_graph.py --summary    # also print a Markdown summary (for CI step summary)

The HTML file contains a generated region delimited by:
    /*__DATA_START__ ... */ ... /*__DATA_END__*/
Only that region (and the "last updated" date) is rewritten; the rendering code
is never touched.
"""
from __future__ import annotations
import sys, re, json, datetime, pathlib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
YAML = HERE / "graph-data.yml"
HTML = HERE / "gaia-knowledge-graph.html"
CHAPTERS = REPO / "book" / "chapters"

DATA_RE = re.compile(r"/\*__DATA_START__.*?\*/.*?/\*__DATA_END__\*/", re.S)
DATE_RE = re.compile(r"last updated \d{4}-\d{2}-\d{2}")


def load():
    import yaml  # pyyaml
    with open(YAML, encoding="utf-8") as f:
        return yaml.safe_load(f)


def validate(data):
    """Return (errors, warnings)."""
    errors, warnings = [], []
    cats = data.get("categories", [])
    nodes = data.get("nodes", [])
    edges = data.get("edges", [])

    subkeys = {s[0] for c in cats for s in c["subs"]}
    ids = [n["id"] for n in nodes]
    idset = set(ids)

    for i in ids:
        if ids.count(i) > 1:
            errors.append(f"duplicate node id: {i}")
    for n in nodes:
        if n["cat"] not in {c["key"] for c in cats}:
            errors.append(f"node {n['id']}: unknown category '{n['cat']}'")
        if n["sub"] not in subkeys:
            errors.append(f"node {n['id']}: unknown subcategory '{n['sub']}'")
    deg = {i: 0 for i in ids}
    for e in edges:
        a, b = e[0], e[1]
        t = e[2] if len(e) > 2 else "f"
        if a not in idset:
            errors.append(f"edge references missing node: {a}")
        if b not in idset:
            errors.append(f"edge references missing node: {b}")
        if t not in {"f", "p", "u", "v", "d"}:
            errors.append(f"edge {a}->{b}: unknown type '{t}'")
        if a in deg:
            deg[a] += 1
        if b in deg:
            deg[b] += 1
    for i, d in deg.items():
        if d == 0:
            warnings.append(f"isolated node (no edges): {i}")
    return errors, warnings


def drift_report(data):
    """Advisory cross-check against the book chapters. Never fails the build."""
    lines = []
    text = ""
    if CHAPTERS.is_dir():
        for md in sorted(CHAPTERS.glob("*.md")):
            text += md.read_text(encoding="utf-8", errors="ignore").lower()

    # 1) graph nodes never mentioned in the docs (possibly stale or undocumented)
    orphan = []
    for n in data["nodes"]:
        if n["cat"] == "hazard":
            continue  # hazards have their own pages / obvious
        # token = first word of the id, plus a distinctive label word
        toks = {n["id"].lower()}
        for w in re.findall(r"[a-zA-Z][a-zA-Z0-9]{3,}", n["label"].lower()):
            toks.add(w)
        if text and not any(t in text for t in toks):
            orphan.append(f"{n['id']} ({n['label']})")

    # 2) gaia-hazlab repos referenced in docs but absent from the graph as a node id
    repos = set(re.findall(r"github\.com/gaia-hazlab/([a-z0-9._-]+)", text))
    node_ids = {n["id"] for n in data["nodes"]}
    repo_hint = sorted(r for r in repos if r.replace("-", "").replace("_", "")
                       not in {i.replace("-", "").replace("_", "") for i in node_ids})

    lines.append(f"- nodes: {len(data['nodes'])}, edges: {len(data['edges'])}")
    lines.append(f"- graph nodes not found in any chapter (review): "
                 + (", ".join(orphan) if orphan else "none"))
    lines.append(f"- gaia-hazlab repos in docs not represented as a node id (info only): "
                 + (", ".join(repo_hint) if repo_hint else "none"))
    return "\n".join(lines)


def emit_block(data):
    cats = json.dumps(data["categories"], ensure_ascii=False)
    nodes = json.dumps(data["nodes"], ensure_ascii=False)
    edges = json.dumps(data["edges"], ensure_ascii=False)
    return ("/*__DATA_START__  generated by build_graph.py from graph-data.yml "
            "— DO NOT EDIT BY HAND  */\n"
            f"const CATS={cats};\n"
            f"const N={nodes};\n"
            f"const E={edges};\n"
            "/*__DATA_END__*/")


def main(argv):
    check_only = "--check" in argv
    want_summary = "--summary" in argv

    data = load()
    errors, warnings = validate(data)
    for w in warnings:
        print(f"WARN: {w}", file=sys.stderr)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    report = drift_report(data)
    print(report, file=sys.stderr)

    if not check_only:
        html = HTML.read_text(encoding="utf-8")
        if not DATA_RE.search(html):
            print("ERROR: data markers not found in gaia-knowledge-graph.html", file=sys.stderr)
            return 1
        today = datetime.date.today().isoformat()
        html = DATA_RE.sub(lambda m: emit_block(data), html)
        html = DATE_RE.sub(f"last updated {today}", html)
        HTML.write_text(html, encoding="utf-8")
        print(f"Regenerated {HTML.name} ({len(data['nodes'])} nodes, "
              f"{len(data['edges'])} edges) — last updated {today}.", file=sys.stderr)

    if want_summary:
        print("### GAIA knowledge graph regenerated\n")
        print(report.replace("- ", "- "))
        if warnings:
            print("\n**Warnings**\n")
            for w in warnings:
                print(f"- {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
